# Generated by Django 4.1 on 2022-08-12 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Locales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clee', models.CharField(blank=True, max_length=200, null=True, verbose_name='CLEE')),
                ('idLocal', models.CharField(blank=True, max_length=50, null=True, verbose_name='Id del local')),
                ('nombreLocal', models.CharField(blank=True, max_length=200, null=True, verbose_name='Nombre del local')),
                ('razonSocial', models.CharField(blank=True, max_length=200, null=True, verbose_name='Razon social')),
                ('nombreActividad', models.CharField(blank=True, max_length=200, null=True, verbose_name='Nombre de la actividad')),
                ('Personal', models.CharField(blank=True, max_length=50, null=True, verbose_name='Personal ocupado')),
                ('tipoVialidad', models.CharField(blank=True, max_length=50, null=True, verbose_name='Tipo de Vialidad')),
                ('nombreVialidad', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre de la vialidad')),
                ('numeroExterior', models.CharField(blank=True, max_length=50, null=True, verbose_name='Numero Exterior')),
                ('numeroInterior', models.CharField(blank=True, max_length=50, null=True, verbose_name='Numero Interior')),
                ('nombreAsentamiento', models.CharField(blank=True, max_length=50, null=True, verbose_name='Nombre del Asentamiento Humano')),
                ('codigoPostal', models.CharField(blank=True, max_length=50, null=True, verbose_name='Codigo Postal')),
                ('Entidad', models.CharField(blank=True, max_length=50, null=True, verbose_name='Entidad')),
                ('Telefono', models.CharField(blank=True, max_length=50, null=True, verbose_name='Numero de Telefono')),
                ('Correo', models.CharField(blank=True, max_length=100, null=True, verbose_name='Correo Electronico')),
                ('sitioInternet', models.CharField(blank=True, max_length=50, null=True, verbose_name='Sitio de Internet')),
                ('tipoUnidadEconomica', models.CharField(blank=True, max_length=50, null=True, verbose_name='Tipo de unidad Economica')),
                ('Longitud', models.CharField(blank=True, max_length=100, null=True, verbose_name='Longitud')),
                ('Latitud', models.CharField(max_length=50, verbose_name='Latitud')),
                ('centroComercial', models.CharField(blank=True, max_length=200, null=True, verbose_name='Centro Comercial')),
                ('tipoCentroComercial', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tipo de Centro Comercial')),
                ('numeroLocal', models.CharField(blank=True, max_length=50, null=True, verbose_name='Numero de Local')),
            ],
        ),
    ]
