# Generated by Django 4.1 on 2022-09-20 20:56

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Locales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='locales',
            name='punto',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
    ]
