# Generated by Django 4.1 on 2022-09-23 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Locales', '0002_locales_punto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='locales',
            old_name='clee',
            new_name='CLEE',
        ),
        migrations.RenameField(
            model_name='locales',
            old_name='codigoPostal',
            new_name='CP',
        ),
        migrations.RenameField(
            model_name='locales',
            old_name='nombreVialidad',
            new_name='Calle',
        ),
        migrations.RenameField(
            model_name='locales',
            old_name='centroComercial',
            new_name='CentroComercial',
        ),
        migrations.RenameField(
            model_name='locales',
            old_name='nombreActividad',
            new_name='Clase_actividad',
        ),
        migrations.RenameField(
            model_name='locales',
            old_name='nombreAsentamiento',
            new_name='Colonia',
        ),
        migrations.RenameField(
            model_name='locales',
            old_name='Correo',
            new_name='Correo_e',
        ),
        migrations.RenameField(
            model_name='locales',
            old_name='Personal',
            new_name='Estrato',
        ),
        migrations.RenameField(
            model_name='locales',
            old_name='idLocal',
            new_name='Id',
        ),
        migrations.RenameField(
            model_name='locales',
            old_name='nombreLocal',
            new_name='Nombre',
        ),
        migrations.RenameField(
            model_name='locales',
            old_name='numeroLocal',
            new_name='NumLocal',
        ),
        migrations.RenameField(
            model_name='locales',
            old_name='numeroExterior',
            new_name='Num_Exterior',
        ),
        migrations.RenameField(
            model_name='locales',
            old_name='numeroInterior',
            new_name='Num_Interior',
        ),
        migrations.RenameField(
            model_name='locales',
            old_name='razonSocial',
            new_name='Razon_social',
        ),
        migrations.RenameField(
            model_name='locales',
            old_name='sitioInternet',
            new_name='Sitio_internet',
        ),
        migrations.RenameField(
            model_name='locales',
            old_name='tipoUnidadEconomica',
            new_name='Tipo',
        ),
        migrations.RenameField(
            model_name='locales',
            old_name='tipoCentroComercial',
            new_name='TipoCentroComercial',
        ),
        migrations.RenameField(
            model_name='locales',
            old_name='tipoVialidad',
            new_name='Tipo_vialidad',
        ),
        migrations.RenameField(
            model_name='locales',
            old_name='Entidad',
            new_name='Ubicacion',
        ),
    ]
