# Generated by Django 4.1 on 2022-12-07 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='empresa',
            field=models.BooleanField(default=False),
        ),
    ]
